# Default values for ks-crds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kubectl:
  image:
    registry: ""
    repository: kubesphere/kubectl
    tag: "v1.27.16"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 100Mi
