/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta2 "kubesphere.io/api/types/v1beta2"
)

// FakeFederatedNotificationManagers implements FederatedNotificationManagerInterface
type FakeFederatedNotificationManagers struct {
	Fake *FakeTypesV1beta2
}

var federatednotificationmanagersResource = schema.GroupVersionResource{Group: "types.kubefed.io", Version: "v1beta2", Resource: "federatednotificationmanagers"}

var federatednotificationmanagersKind = schema.GroupVersionKind{Group: "types.kubefed.io", Version: "v1beta2", Kind: "FederatedNotificationManager"}

// Get takes name of the federatedNotificationManager, and returns the corresponding federatedNotificationManager object, and an error if there is any.
func (c *FakeFederatedNotificationManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.FederatedNotificationManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(federatednotificationmanagersResource, name), &v1beta2.FederatedNotificationManager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.FederatedNotificationManager), err
}

// List takes label and field selectors, and returns the list of FederatedNotificationManagers that match those selectors.
func (c *FakeFederatedNotificationManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.FederatedNotificationManagerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(federatednotificationmanagersResource, federatednotificationmanagersKind, opts), &v1beta2.FederatedNotificationManagerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.FederatedNotificationManagerList{ListMeta: obj.(*v1beta2.FederatedNotificationManagerList).ListMeta}
	for _, item := range obj.(*v1beta2.FederatedNotificationManagerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedNotificationManagers.
func (c *FakeFederatedNotificationManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(federatednotificationmanagersResource, opts))
}

// Create takes the representation of a federatedNotificationManager and creates it.  Returns the server's representation of the federatedNotificationManager, and an error, if there is any.
func (c *FakeFederatedNotificationManagers) Create(ctx context.Context, federatedNotificationManager *v1beta2.FederatedNotificationManager, opts v1.CreateOptions) (result *v1beta2.FederatedNotificationManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(federatednotificationmanagersResource, federatedNotificationManager), &v1beta2.FederatedNotificationManager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.FederatedNotificationManager), err
}

// Update takes the representation of a federatedNotificationManager and updates it. Returns the server's representation of the federatedNotificationManager, and an error, if there is any.
func (c *FakeFederatedNotificationManagers) Update(ctx context.Context, federatedNotificationManager *v1beta2.FederatedNotificationManager, opts v1.UpdateOptions) (result *v1beta2.FederatedNotificationManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(federatednotificationmanagersResource, federatedNotificationManager), &v1beta2.FederatedNotificationManager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.FederatedNotificationManager), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFederatedNotificationManagers) UpdateStatus(ctx context.Context, federatedNotificationManager *v1beta2.FederatedNotificationManager, opts v1.UpdateOptions) (*v1beta2.FederatedNotificationManager, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(federatednotificationmanagersResource, "status", federatedNotificationManager), &v1beta2.FederatedNotificationManager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.FederatedNotificationManager), err
}

// Delete takes name of the federatedNotificationManager and deletes it. Returns an error if one occurs.
func (c *FakeFederatedNotificationManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(federatednotificationmanagersResource, name), &v1beta2.FederatedNotificationManager{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedNotificationManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(federatednotificationmanagersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta2.FederatedNotificationManagerList{})
	return err
}

// Patch applies the patch and returns the patched federatedNotificationManager.
func (c *FakeFederatedNotificationManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.FederatedNotificationManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(federatednotificationmanagersResource, name, pt, data, subresources...), &v1beta2.FederatedNotificationManager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.FederatedNotificationManager), err
}
