# Copyright 2025 The KubeSphere Authors.
# SPDX-License-Identifier: LicenseRef-KubeSphere-Open-Source
header:
  license:
    spdx-id: LicenseRef-KubeSphere-Open-Source
    copyright-year: '2025'
    copyright-owner: KubeSphere Authors
    content: |
      Copyright [year] The [owner].
      SPDX-License-Identifier: LicenseRef-KubeSphere-Open-Source
  paths:
    - "pkg"
    - "staging"
    - "tools"
  paths-ignore:
    - "LICENSE"
    - "OWNERS"
    - "go.sum"
  comment: on-failure
  license-location-threshold: 80
  language:
    Go:
      extensions:
        - ".go"
      comment_style_id: DoubleSlash
