FROM alpine:3.6

RUN apk add --update ca-certificates \
    && update-ca-certificates \ 
    && mkdir -p /etc/kubesphere/ingress-controller

COPY ./bin/* /usr/local/bin/
COPY ./install/ingress-controller /etc/kubesphere/ingress-controller
COPY ./install/swagger-ui        /usr/lib/kubesphere/swagger-ui
CMD ["sh"]
