FROM alpine:3.6

RUN apk add --update ca-certificates \
    && update-ca-certificates \ 
    && mkdir -p /etc/kubesphere/ingress-controller

COPY ./bin/* /usr/local/bin/
COPY ./ingress-controller /etc/kubesphere/ingress-controller

CMD ["sh"]
