/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1beta1 "kubesphere.io/kubesphere/pkg/apis/types/v1beta1"
)

// FederatedNamespaceLister helps list FederatedNamespaces.
type FederatedNamespaceLister interface {
	// List lists all FederatedNamespaces in the indexer.
	List(selector labels.Selector) (ret []*v1beta1.FederatedNamespace, err error)
	// Get retrieves the FederatedNamespace from the index for a given name.
	Get(name string) (*v1beta1.FederatedNamespace, error)
	FederatedNamespaceListerExpansion
}

// federatedNamespaceLister implements the FederatedNamespaceLister interface.
type federatedNamespaceLister struct {
	indexer cache.Indexer
}

// NewFederatedNamespaceLister returns a new FederatedNamespaceLister.
func NewFederatedNamespaceLister(indexer cache.Indexer) FederatedNamespaceLister {
	return &federatedNamespaceLister{indexer: indexer}
}

// List lists all FederatedNamespaces in the indexer.
func (s *federatedNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.FederatedNamespace, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.FederatedNamespace))
	})
	return ret, err
}

// Get retrieves the FederatedNamespace from the index for a given name.
func (s *federatedNamespaceLister) Get(name string) (*v1beta1.FederatedNamespace, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("federatednamespace"), name)
	}
	return obj.(*v1beta1.FederatedNamespace), nil
}
