apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: devopsprojectrolebindings.devops.kubesphere.io
spec:
  group: devops.kubesphere.io
  names:
    kind: DevOpsProjectRoleBinding
    plural: devopsprojectrolebindings
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            roleRef:
              description: RoleRef can reference a Role in the current namespace or
                a ClusterRole in the global namespace. If the RoleRef cannot be resolved,
                the Authorizer must return an error.
              type: object
            subjects:
              description: Subjects holds references to the objects the role applies
                to.
              items:
                type: object
              type: array
          required:
          - roleRef
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
