apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: workspacenetworkpolicies.network.kubesphere.io
spec:
  group: network.kubesphere.io
  names:
    kind: WorkspaceNetworkPolicy
    plural: workspacenetworkpolicies
  scope: ""
  validation:
    openAPIV3Schema:
      description: WorkspaceNetworkPolicy is the Schema for the workspacenetworkpolicies
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkspaceNetworkPolicySpec defines the desired state of WorkspaceNetworkPolicy
          type: object
        status:
          description: WorkspaceNetworkPolicyStatus defines the observed state of
            WorkspaceNetworkPolicy
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
