/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v2 "kubesphere.io/kubesphere/pkg/apis/notification/v2"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// DingTalkReceiversGetter has a method to return a DingTalkReceiverInterface.
// A group's client should implement this interface.
type DingTalkReceiversGetter interface {
	DingTalkReceivers() DingTalkReceiverInterface
}

// DingTalkReceiverInterface has methods to work with DingTalkReceiver resources.
type DingTalkReceiverInterface interface {
	Create(ctx context.Context, dingTalkReceiver *v2.DingTalkReceiver, opts v1.CreateOptions) (*v2.DingTalkReceiver, error)
	Update(ctx context.Context, dingTalkReceiver *v2.DingTalkReceiver, opts v1.UpdateOptions) (*v2.DingTalkReceiver, error)
	UpdateStatus(ctx context.Context, dingTalkReceiver *v2.DingTalkReceiver, opts v1.UpdateOptions) (*v2.DingTalkReceiver, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.DingTalkReceiver, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.DingTalkReceiverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.DingTalkReceiver, err error)
	DingTalkReceiverExpansion
}

// dingTalkReceivers implements DingTalkReceiverInterface
type dingTalkReceivers struct {
	client rest.Interface
}

// newDingTalkReceivers returns a DingTalkReceivers
func newDingTalkReceivers(c *NotificationV2Client) *dingTalkReceivers {
	return &dingTalkReceivers{
		client: c.RESTClient(),
	}
}

// Get takes name of the dingTalkReceiver, and returns the corresponding dingTalkReceiver object, and an error if there is any.
func (c *dingTalkReceivers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.DingTalkReceiver, err error) {
	result = &v2.DingTalkReceiver{}
	err = c.client.Get().
		Resource("dingtalkreceivers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DingTalkReceivers that match those selectors.
func (c *dingTalkReceivers) List(ctx context.Context, opts v1.ListOptions) (result *v2.DingTalkReceiverList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2.DingTalkReceiverList{}
	err = c.client.Get().
		Resource("dingtalkreceivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dingTalkReceivers.
func (c *dingTalkReceivers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dingtalkreceivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dingTalkReceiver and creates it.  Returns the server's representation of the dingTalkReceiver, and an error, if there is any.
func (c *dingTalkReceivers) Create(ctx context.Context, dingTalkReceiver *v2.DingTalkReceiver, opts v1.CreateOptions) (result *v2.DingTalkReceiver, err error) {
	result = &v2.DingTalkReceiver{}
	err = c.client.Post().
		Resource("dingtalkreceivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dingTalkReceiver).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dingTalkReceiver and updates it. Returns the server's representation of the dingTalkReceiver, and an error, if there is any.
func (c *dingTalkReceivers) Update(ctx context.Context, dingTalkReceiver *v2.DingTalkReceiver, opts v1.UpdateOptions) (result *v2.DingTalkReceiver, err error) {
	result = &v2.DingTalkReceiver{}
	err = c.client.Put().
		Resource("dingtalkreceivers").
		Name(dingTalkReceiver.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dingTalkReceiver).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dingTalkReceivers) UpdateStatus(ctx context.Context, dingTalkReceiver *v2.DingTalkReceiver, opts v1.UpdateOptions) (result *v2.DingTalkReceiver, err error) {
	result = &v2.DingTalkReceiver{}
	err = c.client.Put().
		Resource("dingtalkreceivers").
		Name(dingTalkReceiver.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dingTalkReceiver).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dingTalkReceiver and deletes it. Returns an error if one occurs.
func (c *dingTalkReceivers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dingtalkreceivers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dingTalkReceivers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dingtalkreceivers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dingTalkReceiver.
func (c *dingTalkReceivers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.DingTalkReceiver, err error) {
	result = &v2.DingTalkReceiver{}
	err = c.client.Patch(pt).
		Resource("dingtalkreceivers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
