/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/application/v1alpha1"
)

// FakeOperatorApplications implements OperatorApplicationInterface
type FakeOperatorApplications struct {
	Fake *FakeApplicationV1alpha1
}

var operatorapplicationsResource = schema.GroupVersionResource{Group: "application.kubesphere.io", Version: "v1alpha1", Resource: "operatorapplications"}

var operatorapplicationsKind = schema.GroupVersionKind{Group: "application.kubesphere.io", Version: "v1alpha1", Kind: "OperatorApplication"}

// Get takes name of the operatorApplication, and returns the corresponding operatorApplication object, and an error if there is any.
func (c *FakeOperatorApplications) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OperatorApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(operatorapplicationsResource, name), &v1alpha1.OperatorApplication{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplication), err
}

// List takes label and field selectors, and returns the list of OperatorApplications that match those selectors.
func (c *FakeOperatorApplications) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OperatorApplicationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(operatorapplicationsResource, operatorapplicationsKind, opts), &v1alpha1.OperatorApplicationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OperatorApplicationList{ListMeta: obj.(*v1alpha1.OperatorApplicationList).ListMeta}
	for _, item := range obj.(*v1alpha1.OperatorApplicationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operatorApplications.
func (c *FakeOperatorApplications) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(operatorapplicationsResource, opts))
}

// Create takes the representation of a operatorApplication and creates it.  Returns the server's representation of the operatorApplication, and an error, if there is any.
func (c *FakeOperatorApplications) Create(ctx context.Context, operatorApplication *v1alpha1.OperatorApplication, opts v1.CreateOptions) (result *v1alpha1.OperatorApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(operatorapplicationsResource, operatorApplication), &v1alpha1.OperatorApplication{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplication), err
}

// Update takes the representation of a operatorApplication and updates it. Returns the server's representation of the operatorApplication, and an error, if there is any.
func (c *FakeOperatorApplications) Update(ctx context.Context, operatorApplication *v1alpha1.OperatorApplication, opts v1.UpdateOptions) (result *v1alpha1.OperatorApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(operatorapplicationsResource, operatorApplication), &v1alpha1.OperatorApplication{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplication), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOperatorApplications) UpdateStatus(ctx context.Context, operatorApplication *v1alpha1.OperatorApplication, opts v1.UpdateOptions) (*v1alpha1.OperatorApplication, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(operatorapplicationsResource, "status", operatorApplication), &v1alpha1.OperatorApplication{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplication), err
}

// Delete takes name of the operatorApplication and deletes it. Returns an error if one occurs.
func (c *FakeOperatorApplications) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(operatorapplicationsResource, name), &v1alpha1.OperatorApplication{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOperatorApplications) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(operatorapplicationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OperatorApplicationList{})
	return err
}

// Patch applies the patch and returns the patched operatorApplication.
func (c *FakeOperatorApplications) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OperatorApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(operatorapplicationsResource, name, pt, data, subresources...), &v1alpha1.OperatorApplication{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplication), err
}
