/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/application/v1alpha1"
)

// FakeOperatorApplicationVersions implements OperatorApplicationVersionInterface
type FakeOperatorApplicationVersions struct {
	Fake *FakeApplicationV1alpha1
}

var operatorapplicationversionsResource = schema.GroupVersionResource{Group: "application.kubesphere.io", Version: "v1alpha1", Resource: "operatorapplicationversions"}

var operatorapplicationversionsKind = schema.GroupVersionKind{Group: "application.kubesphere.io", Version: "v1alpha1", Kind: "OperatorApplicationVersion"}

// Get takes name of the operatorApplicationVersion, and returns the corresponding operatorApplicationVersion object, and an error if there is any.
func (c *FakeOperatorApplicationVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OperatorApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(operatorapplicationversionsResource, name), &v1alpha1.OperatorApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplicationVersion), err
}

// List takes label and field selectors, and returns the list of OperatorApplicationVersions that match those selectors.
func (c *FakeOperatorApplicationVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OperatorApplicationVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(operatorapplicationversionsResource, operatorapplicationversionsKind, opts), &v1alpha1.OperatorApplicationVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OperatorApplicationVersionList{ListMeta: obj.(*v1alpha1.OperatorApplicationVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.OperatorApplicationVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operatorApplicationVersions.
func (c *FakeOperatorApplicationVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(operatorapplicationversionsResource, opts))
}

// Create takes the representation of a operatorApplicationVersion and creates it.  Returns the server's representation of the operatorApplicationVersion, and an error, if there is any.
func (c *FakeOperatorApplicationVersions) Create(ctx context.Context, operatorApplicationVersion *v1alpha1.OperatorApplicationVersion, opts v1.CreateOptions) (result *v1alpha1.OperatorApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(operatorapplicationversionsResource, operatorApplicationVersion), &v1alpha1.OperatorApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplicationVersion), err
}

// Update takes the representation of a operatorApplicationVersion and updates it. Returns the server's representation of the operatorApplicationVersion, and an error, if there is any.
func (c *FakeOperatorApplicationVersions) Update(ctx context.Context, operatorApplicationVersion *v1alpha1.OperatorApplicationVersion, opts v1.UpdateOptions) (result *v1alpha1.OperatorApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(operatorapplicationversionsResource, operatorApplicationVersion), &v1alpha1.OperatorApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplicationVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOperatorApplicationVersions) UpdateStatus(ctx context.Context, operatorApplicationVersion *v1alpha1.OperatorApplicationVersion, opts v1.UpdateOptions) (*v1alpha1.OperatorApplicationVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(operatorapplicationversionsResource, "status", operatorApplicationVersion), &v1alpha1.OperatorApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplicationVersion), err
}

// Delete takes name of the operatorApplicationVersion and deletes it. Returns an error if one occurs.
func (c *FakeOperatorApplicationVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(operatorapplicationversionsResource, name), &v1alpha1.OperatorApplicationVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOperatorApplicationVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(operatorapplicationversionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OperatorApplicationVersionList{})
	return err
}

// Patch applies the patch and returns the patched operatorApplicationVersion.
func (c *FakeOperatorApplicationVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OperatorApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(operatorapplicationversionsResource, name, pt, data, subresources...), &v1alpha1.OperatorApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatorApplicationVersion), err
}
