/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/kubesphere/pkg/apis/application/v1alpha1"
)

// FakeHelmAudits implements HelmAuditInterface
type FakeHelmAudits struct {
	Fake *FakeApplicationV1alpha1
}

var helmauditsResource = schema.GroupVersionResource{Group: "application.kubesphere.io", Version: "v1alpha1", Resource: "helmaudits"}

var helmauditsKind = schema.GroupVersionKind{Group: "application.kubesphere.io", Version: "v1alpha1", Kind: "HelmAudit"}

// Get takes name of the helmAudit, and returns the corresponding helmAudit object, and an error if there is any.
func (c *FakeHelmAudits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HelmAudit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(helmauditsResource, name), &v1alpha1.HelmAudit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmAudit), err
}

// List takes label and field selectors, and returns the list of HelmAudits that match those selectors.
func (c *FakeHelmAudits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HelmAuditList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(helmauditsResource, helmauditsKind, opts), &v1alpha1.HelmAuditList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HelmAuditList{ListMeta: obj.(*v1alpha1.HelmAuditList).ListMeta}
	for _, item := range obj.(*v1alpha1.HelmAuditList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested helmAudits.
func (c *FakeHelmAudits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(helmauditsResource, opts))
}

// Create takes the representation of a helmAudit and creates it.  Returns the server's representation of the helmAudit, and an error, if there is any.
func (c *FakeHelmAudits) Create(ctx context.Context, helmAudit *v1alpha1.HelmAudit, opts v1.CreateOptions) (result *v1alpha1.HelmAudit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(helmauditsResource, helmAudit), &v1alpha1.HelmAudit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmAudit), err
}

// Update takes the representation of a helmAudit and updates it. Returns the server's representation of the helmAudit, and an error, if there is any.
func (c *FakeHelmAudits) Update(ctx context.Context, helmAudit *v1alpha1.HelmAudit, opts v1.UpdateOptions) (result *v1alpha1.HelmAudit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(helmauditsResource, helmAudit), &v1alpha1.HelmAudit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmAudit), err
}

// Delete takes name of the helmAudit and deletes it. Returns an error if one occurs.
func (c *FakeHelmAudits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(helmauditsResource, name), &v1alpha1.HelmAudit{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHelmAudits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(helmauditsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HelmAuditList{})
	return err
}

// Patch applies the patch and returns the patched helmAudit.
func (c *FakeHelmAudits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HelmAudit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(helmauditsResource, name, pt, data, subresources...), &v1alpha1.HelmAudit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmAudit), err
}
