apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ingress-role-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubesphere-router-role
subjects:
  - kind: ServiceAccount
    name: kubesphere-router-serviceaccount
