/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/extensions/v1alpha1"
)

// FakeJSBundles implements JSBundleInterface
type FakeJSBundles struct {
	Fake *FakeExtensionsV1alpha1
}

var jsbundlesResource = schema.GroupVersionResource{Group: "extensions.kubesphere.io", Version: "v1alpha1", Resource: "jsbundles"}

var jsbundlesKind = schema.GroupVersionKind{Group: "extensions.kubesphere.io", Version: "v1alpha1", Kind: "JSBundle"}

// Get takes name of the jSBundle, and returns the corresponding jSBundle object, and an error if there is any.
func (c *FakeJSBundles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JSBundle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(jsbundlesResource, name), &v1alpha1.JSBundle{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JSBundle), err
}

// List takes label and field selectors, and returns the list of JSBundles that match those selectors.
func (c *FakeJSBundles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JSBundleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(jsbundlesResource, jsbundlesKind, opts), &v1alpha1.JSBundleList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JSBundleList{ListMeta: obj.(*v1alpha1.JSBundleList).ListMeta}
	for _, item := range obj.(*v1alpha1.JSBundleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jSBundles.
func (c *FakeJSBundles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(jsbundlesResource, opts))
}

// Create takes the representation of a jSBundle and creates it.  Returns the server's representation of the jSBundle, and an error, if there is any.
func (c *FakeJSBundles) Create(ctx context.Context, jSBundle *v1alpha1.JSBundle, opts v1.CreateOptions) (result *v1alpha1.JSBundle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(jsbundlesResource, jSBundle), &v1alpha1.JSBundle{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JSBundle), err
}

// Update takes the representation of a jSBundle and updates it. Returns the server's representation of the jSBundle, and an error, if there is any.
func (c *FakeJSBundles) Update(ctx context.Context, jSBundle *v1alpha1.JSBundle, opts v1.UpdateOptions) (result *v1alpha1.JSBundle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(jsbundlesResource, jSBundle), &v1alpha1.JSBundle{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JSBundle), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJSBundles) UpdateStatus(ctx context.Context, jSBundle *v1alpha1.JSBundle, opts v1.UpdateOptions) (*v1alpha1.JSBundle, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(jsbundlesResource, "status", jSBundle), &v1alpha1.JSBundle{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JSBundle), err
}

// Delete takes name of the jSBundle and deletes it. Returns an error if one occurs.
func (c *FakeJSBundles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(jsbundlesResource, name), &v1alpha1.JSBundle{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJSBundles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(jsbundlesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.JSBundleList{})
	return err
}

// Patch applies the patch and returns the patched jSBundle.
func (c *FakeJSBundles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JSBundle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(jsbundlesResource, name, pt, data, subresources...), &v1alpha1.JSBundle{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JSBundle), err
}
