/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubesphere.io/api/application/v1alpha1"
)

// OperatorApplicationLister helps list OperatorApplications.
// All objects returned here must be treated as read-only.
type OperatorApplicationLister interface {
	// List lists all OperatorApplications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OperatorApplication, err error)
	// Get retrieves the OperatorApplication from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.OperatorApplication, error)
	OperatorApplicationListerExpansion
}

// operatorApplicationLister implements the OperatorApplicationLister interface.
type operatorApplicationLister struct {
	indexer cache.Indexer
}

// NewOperatorApplicationLister returns a new OperatorApplicationLister.
func NewOperatorApplicationLister(indexer cache.Indexer) OperatorApplicationLister {
	return &operatorApplicationLister{indexer: indexer}
}

// List lists all OperatorApplications in the indexer.
func (s *operatorApplicationLister) List(selector labels.Selector) (ret []*v1alpha1.OperatorApplication, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OperatorApplication))
	})
	return ret, err
}

// Get retrieves the OperatorApplication from the index for a given name.
func (s *operatorApplicationLister) Get(name string) (*v1alpha1.OperatorApplication, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("operatorapplication"), name)
	}
	return obj.(*v1alpha1.OperatorApplication), nil
}
