/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubesphere.io/api/network/v1alpha1"
)

// IPAMHandleLister helps list IPAMHandles.
type IPAMHandleLister interface {
	// List lists all IPAMHandles in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.IPAMHandle, err error)
	// Get retrieves the IPAMHandle from the index for a given name.
	Get(name string) (*v1alpha1.IPAMHandle, error)
	IPAMHandleListerExpansion
}

// iPAMHandleLister implements the IPAMHandleLister interface.
type iPAMHandleLister struct {
	indexer cache.Indexer
}

// NewIPAMHandleLister returns a new IPAMHandleLister.
func NewIPAMHandleLister(indexer cache.Indexer) IPAMHandleLister {
	return &iPAMHandleLister{indexer: indexer}
}

// List lists all IPAMHandles in the indexer.
func (s *iPAMHandleLister) List(selector labels.Selector) (ret []*v1alpha1.IPAMHandle, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IPAMHandle))
	})
	return ret, err
}

// Get retrieves the IPAMHandle from the index for a given name.
func (s *iPAMHandleLister) Get(name string) (*v1alpha1.IPAMHandle, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("ipamhandle"), name)
	}
	return obj.(*v1alpha1.IPAMHandle), nil
}
