/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta2 "kubesphere.io/api/types/v1beta2"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// FederatedNotificationSilencesGetter has a method to return a FederatedNotificationSilenceInterface.
// A group's client should implement this interface.
type FederatedNotificationSilencesGetter interface {
	FederatedNotificationSilences() FederatedNotificationSilenceInterface
}

// FederatedNotificationSilenceInterface has methods to work with FederatedNotificationSilence resources.
type FederatedNotificationSilenceInterface interface {
	Create(ctx context.Context, federatedNotificationSilence *v1beta2.FederatedNotificationSilence, opts v1.CreateOptions) (*v1beta2.FederatedNotificationSilence, error)
	Update(ctx context.Context, federatedNotificationSilence *v1beta2.FederatedNotificationSilence, opts v1.UpdateOptions) (*v1beta2.FederatedNotificationSilence, error)
	UpdateStatus(ctx context.Context, federatedNotificationSilence *v1beta2.FederatedNotificationSilence, opts v1.UpdateOptions) (*v1beta2.FederatedNotificationSilence, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.FederatedNotificationSilence, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.FederatedNotificationSilenceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.FederatedNotificationSilence, err error)
	FederatedNotificationSilenceExpansion
}

// federatedNotificationSilences implements FederatedNotificationSilenceInterface
type federatedNotificationSilences struct {
	client rest.Interface
}

// newFederatedNotificationSilences returns a FederatedNotificationSilences
func newFederatedNotificationSilences(c *TypesV1beta2Client) *federatedNotificationSilences {
	return &federatedNotificationSilences{
		client: c.RESTClient(),
	}
}

// Get takes name of the federatedNotificationSilence, and returns the corresponding federatedNotificationSilence object, and an error if there is any.
func (c *federatedNotificationSilences) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.FederatedNotificationSilence, err error) {
	result = &v1beta2.FederatedNotificationSilence{}
	err = c.client.Get().
		Resource("federatednotificationsilences").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedNotificationSilences that match those selectors.
func (c *federatedNotificationSilences) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.FederatedNotificationSilenceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.FederatedNotificationSilenceList{}
	err = c.client.Get().
		Resource("federatednotificationsilences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedNotificationSilences.
func (c *federatedNotificationSilences) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("federatednotificationsilences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedNotificationSilence and creates it.  Returns the server's representation of the federatedNotificationSilence, and an error, if there is any.
func (c *federatedNotificationSilences) Create(ctx context.Context, federatedNotificationSilence *v1beta2.FederatedNotificationSilence, opts v1.CreateOptions) (result *v1beta2.FederatedNotificationSilence, err error) {
	result = &v1beta2.FederatedNotificationSilence{}
	err = c.client.Post().
		Resource("federatednotificationsilences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedNotificationSilence).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedNotificationSilence and updates it. Returns the server's representation of the federatedNotificationSilence, and an error, if there is any.
func (c *federatedNotificationSilences) Update(ctx context.Context, federatedNotificationSilence *v1beta2.FederatedNotificationSilence, opts v1.UpdateOptions) (result *v1beta2.FederatedNotificationSilence, err error) {
	result = &v1beta2.FederatedNotificationSilence{}
	err = c.client.Put().
		Resource("federatednotificationsilences").
		Name(federatedNotificationSilence.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedNotificationSilence).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedNotificationSilences) UpdateStatus(ctx context.Context, federatedNotificationSilence *v1beta2.FederatedNotificationSilence, opts v1.UpdateOptions) (result *v1beta2.FederatedNotificationSilence, err error) {
	result = &v1beta2.FederatedNotificationSilence{}
	err = c.client.Put().
		Resource("federatednotificationsilences").
		Name(federatedNotificationSilence.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedNotificationSilence).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedNotificationSilence and deletes it. Returns an error if one occurs.
func (c *federatedNotificationSilences) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("federatednotificationsilences").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedNotificationSilences) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("federatednotificationsilences").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedNotificationSilence.
func (c *federatedNotificationSilences) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.FederatedNotificationSilence, err error) {
	result = &v1beta2.FederatedNotificationSilence{}
	err = c.client.Patch(pt).
		Resource("federatednotificationsilences").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
