apiVersion: data.fluid.io/v1alpha1
kind: DataLoad
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  dataset:
    name: {{datasetName}}
    namespace: {{datasetNamespace}}
  loadMetadata: false
  target:
    - path: {{targetPath}}
