apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  mounts:
    - mountPoint: {{mountPoint}}
      name: {{mountName}}
---
apiVersion: data.fluid.io/v1alpha1
kind: JuiceFSRuntime
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  volume:
    name: {{juicefsVolume}}
    secret: {{secretName}}
