/*
Copyright 2019 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubesphere.io/kubesphere/pkg/apis/devops/v1alpha1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// DevOpsProjectRolesGetter has a method to return a DevOpsProjectRoleInterface.
// A group's client should implement this interface.
type DevOpsProjectRolesGetter interface {
	DevOpsProjectRoles() DevOpsProjectRoleInterface
}

// DevOpsProjectRoleInterface has methods to work with DevOpsProjectRole resources.
type DevOpsProjectRoleInterface interface {
	Create(*v1alpha1.DevOpsProjectRole) (*v1alpha1.DevOpsProjectRole, error)
	Update(*v1alpha1.DevOpsProjectRole) (*v1alpha1.DevOpsProjectRole, error)
	UpdateStatus(*v1alpha1.DevOpsProjectRole) (*v1alpha1.DevOpsProjectRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DevOpsProjectRole, error)
	List(opts v1.ListOptions) (*v1alpha1.DevOpsProjectRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DevOpsProjectRole, err error)
	DevOpsProjectRoleExpansion
}

// devOpsProjectRoles implements DevOpsProjectRoleInterface
type devOpsProjectRoles struct {
	client rest.Interface
}

// newDevOpsProjectRoles returns a DevOpsProjectRoles
func newDevOpsProjectRoles(c *DevopsV1alpha1Client) *devOpsProjectRoles {
	return &devOpsProjectRoles{
		client: c.RESTClient(),
	}
}

// Get takes name of the devOpsProjectRole, and returns the corresponding devOpsProjectRole object, and an error if there is any.
func (c *devOpsProjectRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.DevOpsProjectRole, err error) {
	result = &v1alpha1.DevOpsProjectRole{}
	err = c.client.Get().
		Resource("devopsprojectroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DevOpsProjectRoles that match those selectors.
func (c *devOpsProjectRoles) List(opts v1.ListOptions) (result *v1alpha1.DevOpsProjectRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DevOpsProjectRoleList{}
	err = c.client.Get().
		Resource("devopsprojectroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested devOpsProjectRoles.
func (c *devOpsProjectRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("devopsprojectroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a devOpsProjectRole and creates it.  Returns the server's representation of the devOpsProjectRole, and an error, if there is any.
func (c *devOpsProjectRoles) Create(devOpsProjectRole *v1alpha1.DevOpsProjectRole) (result *v1alpha1.DevOpsProjectRole, err error) {
	result = &v1alpha1.DevOpsProjectRole{}
	err = c.client.Post().
		Resource("devopsprojectroles").
		Body(devOpsProjectRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a devOpsProjectRole and updates it. Returns the server's representation of the devOpsProjectRole, and an error, if there is any.
func (c *devOpsProjectRoles) Update(devOpsProjectRole *v1alpha1.DevOpsProjectRole) (result *v1alpha1.DevOpsProjectRole, err error) {
	result = &v1alpha1.DevOpsProjectRole{}
	err = c.client.Put().
		Resource("devopsprojectroles").
		Name(devOpsProjectRole.Name).
		Body(devOpsProjectRole).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *devOpsProjectRoles) UpdateStatus(devOpsProjectRole *v1alpha1.DevOpsProjectRole) (result *v1alpha1.DevOpsProjectRole, err error) {
	result = &v1alpha1.DevOpsProjectRole{}
	err = c.client.Put().
		Resource("devopsprojectroles").
		Name(devOpsProjectRole.Name).
		SubResource("status").
		Body(devOpsProjectRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the devOpsProjectRole and deletes it. Returns an error if one occurs.
func (c *devOpsProjectRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("devopsprojectroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *devOpsProjectRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("devopsprojectroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched devOpsProjectRole.
func (c *devOpsProjectRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DevOpsProjectRole, err error) {
	result = &v1alpha1.DevOpsProjectRole{}
	err = c.client.Patch(pt).
		Resource("devopsprojectroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
