#!/bin/bash

cat ~/.docker/config.json | grep index.docker.io
if [[ $? != 0 ]]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
fi
docker push kubespheredev/ks-apiserver:latest
