/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "kubesphere.io/api/types/v1beta1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// FederatedGroupBindingsGetter has a method to return a FederatedGroupBindingInterface.
// A group's client should implement this interface.
type FederatedGroupBindingsGetter interface {
	FederatedGroupBindings() FederatedGroupBindingInterface
}

// FederatedGroupBindingInterface has methods to work with FederatedGroupBinding resources.
type FederatedGroupBindingInterface interface {
	Create(ctx context.Context, federatedGroupBinding *v1beta1.FederatedGroupBinding, opts v1.CreateOptions) (*v1beta1.FederatedGroupBinding, error)
	Update(ctx context.Context, federatedGroupBinding *v1beta1.FederatedGroupBinding, opts v1.UpdateOptions) (*v1beta1.FederatedGroupBinding, error)
	UpdateStatus(ctx context.Context, federatedGroupBinding *v1beta1.FederatedGroupBinding, opts v1.UpdateOptions) (*v1beta1.FederatedGroupBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.FederatedGroupBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FederatedGroupBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedGroupBinding, err error)
	FederatedGroupBindingExpansion
}

// federatedGroupBindings implements FederatedGroupBindingInterface
type federatedGroupBindings struct {
	client rest.Interface
}

// newFederatedGroupBindings returns a FederatedGroupBindings
func newFederatedGroupBindings(c *TypesV1beta1Client) *federatedGroupBindings {
	return &federatedGroupBindings{
		client: c.RESTClient(),
	}
}

// Get takes name of the federatedGroupBinding, and returns the corresponding federatedGroupBinding object, and an error if there is any.
func (c *federatedGroupBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FederatedGroupBinding, err error) {
	result = &v1beta1.FederatedGroupBinding{}
	err = c.client.Get().
		Resource("federatedgroupbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedGroupBindings that match those selectors.
func (c *federatedGroupBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FederatedGroupBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.FederatedGroupBindingList{}
	err = c.client.Get().
		Resource("federatedgroupbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedGroupBindings.
func (c *federatedGroupBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("federatedgroupbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedGroupBinding and creates it.  Returns the server's representation of the federatedGroupBinding, and an error, if there is any.
func (c *federatedGroupBindings) Create(ctx context.Context, federatedGroupBinding *v1beta1.FederatedGroupBinding, opts v1.CreateOptions) (result *v1beta1.FederatedGroupBinding, err error) {
	result = &v1beta1.FederatedGroupBinding{}
	err = c.client.Post().
		Resource("federatedgroupbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedGroupBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedGroupBinding and updates it. Returns the server's representation of the federatedGroupBinding, and an error, if there is any.
func (c *federatedGroupBindings) Update(ctx context.Context, federatedGroupBinding *v1beta1.FederatedGroupBinding, opts v1.UpdateOptions) (result *v1beta1.FederatedGroupBinding, err error) {
	result = &v1beta1.FederatedGroupBinding{}
	err = c.client.Put().
		Resource("federatedgroupbindings").
		Name(federatedGroupBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedGroupBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedGroupBindings) UpdateStatus(ctx context.Context, federatedGroupBinding *v1beta1.FederatedGroupBinding, opts v1.UpdateOptions) (result *v1beta1.FederatedGroupBinding, err error) {
	result = &v1beta1.FederatedGroupBinding{}
	err = c.client.Put().
		Resource("federatedgroupbindings").
		Name(federatedGroupBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedGroupBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedGroupBinding and deletes it. Returns an error if one occurs.
func (c *federatedGroupBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("federatedgroupbindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedGroupBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("federatedgroupbindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedGroupBinding.
func (c *federatedGroupBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedGroupBinding, err error) {
	result = &v1beta1.FederatedGroupBinding{}
	err = c.client.Patch(pt).
		Resource("federatedgroupbindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
