/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "kubesphere.io/api/types/v1beta1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// FederatedGroupsGetter has a method to return a FederatedGroupInterface.
// A group's client should implement this interface.
type FederatedGroupsGetter interface {
	FederatedGroups() FederatedGroupInterface
}

// FederatedGroupInterface has methods to work with FederatedGroup resources.
type FederatedGroupInterface interface {
	Create(ctx context.Context, federatedGroup *v1beta1.FederatedGroup, opts v1.CreateOptions) (*v1beta1.FederatedGroup, error)
	Update(ctx context.Context, federatedGroup *v1beta1.FederatedGroup, opts v1.UpdateOptions) (*v1beta1.FederatedGroup, error)
	UpdateStatus(ctx context.Context, federatedGroup *v1beta1.FederatedGroup, opts v1.UpdateOptions) (*v1beta1.FederatedGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.FederatedGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FederatedGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedGroup, err error)
	FederatedGroupExpansion
}

// federatedGroups implements FederatedGroupInterface
type federatedGroups struct {
	client rest.Interface
}

// newFederatedGroups returns a FederatedGroups
func newFederatedGroups(c *TypesV1beta1Client) *federatedGroups {
	return &federatedGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the federatedGroup, and returns the corresponding federatedGroup object, and an error if there is any.
func (c *federatedGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FederatedGroup, err error) {
	result = &v1beta1.FederatedGroup{}
	err = c.client.Get().
		Resource("federatedgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedGroups that match those selectors.
func (c *federatedGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FederatedGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.FederatedGroupList{}
	err = c.client.Get().
		Resource("federatedgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedGroups.
func (c *federatedGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("federatedgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedGroup and creates it.  Returns the server's representation of the federatedGroup, and an error, if there is any.
func (c *federatedGroups) Create(ctx context.Context, federatedGroup *v1beta1.FederatedGroup, opts v1.CreateOptions) (result *v1beta1.FederatedGroup, err error) {
	result = &v1beta1.FederatedGroup{}
	err = c.client.Post().
		Resource("federatedgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedGroup and updates it. Returns the server's representation of the federatedGroup, and an error, if there is any.
func (c *federatedGroups) Update(ctx context.Context, federatedGroup *v1beta1.FederatedGroup, opts v1.UpdateOptions) (result *v1beta1.FederatedGroup, err error) {
	result = &v1beta1.FederatedGroup{}
	err = c.client.Put().
		Resource("federatedgroups").
		Name(federatedGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedGroups) UpdateStatus(ctx context.Context, federatedGroup *v1beta1.FederatedGroup, opts v1.UpdateOptions) (result *v1beta1.FederatedGroup, err error) {
	result = &v1beta1.FederatedGroup{}
	err = c.client.Put().
		Resource("federatedgroups").
		Name(federatedGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedGroup and deletes it. Returns an error if one occurs.
func (c *federatedGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("federatedgroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("federatedgroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedGroup.
func (c *federatedGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedGroup, err error) {
	result = &v1beta1.FederatedGroup{}
	err = c.client.Patch(pt).
		Resource("federatedgroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
