/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "kubesphere.io/kubesphere/pkg/apis/types/v1beta1"
)

// FakeFederatedHelmApplicationVersions implements FederatedHelmApplicationVersionInterface
type FakeFederatedHelmApplicationVersions struct {
	Fake *FakeTypesV1beta1
}

var federatedhelmapplicationversionsResource = schema.GroupVersionResource{Group: "types.kubefed.io", Version: "v1beta1", Resource: "federatedhelmapplicationversions"}

var federatedhelmapplicationversionsKind = schema.GroupVersionKind{Group: "types.kubefed.io", Version: "v1beta1", Kind: "FederatedHelmApplicationVersion"}

// Get takes name of the federatedHelmApplicationVersion, and returns the corresponding federatedHelmApplicationVersion object, and an error if there is any.
func (c *FakeFederatedHelmApplicationVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FederatedHelmApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(federatedhelmapplicationversionsResource, name), &v1beta1.FederatedHelmApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FederatedHelmApplicationVersion), err
}

// List takes label and field selectors, and returns the list of FederatedHelmApplicationVersions that match those selectors.
func (c *FakeFederatedHelmApplicationVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FederatedHelmApplicationVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(federatedhelmapplicationversionsResource, federatedhelmapplicationversionsKind, opts), &v1beta1.FederatedHelmApplicationVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FederatedHelmApplicationVersionList{ListMeta: obj.(*v1beta1.FederatedHelmApplicationVersionList).ListMeta}
	for _, item := range obj.(*v1beta1.FederatedHelmApplicationVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedHelmApplicationVersions.
func (c *FakeFederatedHelmApplicationVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(federatedhelmapplicationversionsResource, opts))
}

// Create takes the representation of a federatedHelmApplicationVersion and creates it.  Returns the server's representation of the federatedHelmApplicationVersion, and an error, if there is any.
func (c *FakeFederatedHelmApplicationVersions) Create(ctx context.Context, federatedHelmApplicationVersion *v1beta1.FederatedHelmApplicationVersion, opts v1.CreateOptions) (result *v1beta1.FederatedHelmApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(federatedhelmapplicationversionsResource, federatedHelmApplicationVersion), &v1beta1.FederatedHelmApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FederatedHelmApplicationVersion), err
}

// Update takes the representation of a federatedHelmApplicationVersion and updates it. Returns the server's representation of the federatedHelmApplicationVersion, and an error, if there is any.
func (c *FakeFederatedHelmApplicationVersions) Update(ctx context.Context, federatedHelmApplicationVersion *v1beta1.FederatedHelmApplicationVersion, opts v1.UpdateOptions) (result *v1beta1.FederatedHelmApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(federatedhelmapplicationversionsResource, federatedHelmApplicationVersion), &v1beta1.FederatedHelmApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FederatedHelmApplicationVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFederatedHelmApplicationVersions) UpdateStatus(ctx context.Context, federatedHelmApplicationVersion *v1beta1.FederatedHelmApplicationVersion, opts v1.UpdateOptions) (*v1beta1.FederatedHelmApplicationVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(federatedhelmapplicationversionsResource, "status", federatedHelmApplicationVersion), &v1beta1.FederatedHelmApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FederatedHelmApplicationVersion), err
}

// Delete takes name of the federatedHelmApplicationVersion and deletes it. Returns an error if one occurs.
func (c *FakeFederatedHelmApplicationVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(federatedhelmapplicationversionsResource, name), &v1beta1.FederatedHelmApplicationVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedHelmApplicationVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(federatedhelmapplicationversionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.FederatedHelmApplicationVersionList{})
	return err
}

// Patch applies the patch and returns the patched federatedHelmApplicationVersion.
func (c *FakeFederatedHelmApplicationVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedHelmApplicationVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(federatedhelmapplicationversionsResource, name, pt, data, subresources...), &v1beta1.FederatedHelmApplicationVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FederatedHelmApplicationVersion), err
}
